//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes_MarketPlace.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Contactu
    {
        public Contactu()
        {
            this.SubmitDate = DateTime.Now;
        }
        public int Id { get; set; }
        [DisplayName("Full Name*")]
        [Required(ErrorMessage = "This field must not be null")]
        public string Name { get; set; }
        [DisplayName("Email Address*")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "This field must not be null")]
        public string Email { get; set; }
        [DisplayName("Subject*")]
        [Required(ErrorMessage = "This field must not be null")]
        public string Subject { get; set; }

        [DisplayName("Comment/Question*")]
        [Required(ErrorMessage = "This field must not be null")]
        public string Comment { get; set; }
        public System.DateTime SubmitDate { get; set; }
    }
}
