//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes_MarketPlace.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Buyer> Buyers { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Contactu> Contactus { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Inappropriate> Inappropriates { get; set; }
        public virtual DbSet<ManageSystem> ManageSystems { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberProfile> MemberProfiles { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Type> Types { get; set; }
    }
}
