//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes_MarketPlace.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Inappropriate
    {
        public Inappropriate()
        {
            this.Date = DateTime.Now;
            this.IsActive = true;
        }
        public int Id { get; set; }
        public int NoteId { get; set; }
        public int OwnerId { get; set; }
        public int MemberId { get; set; }
        public string Remarks { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> DeactivateDate { get; set; }
        public Nullable<int> DeactivateBy { get; set; }
        public bool IsActive { get; set; }

        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual Note Note { get; set; }
    }
}
