//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes_MarketPlace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageSystem
    {
        public int Id { get; set; }
        public string SupportEmail { get; set; }
        public string SupportContactNumber { get; set; }
        public string EmailAddress { get; set; }
        public string EmailPassword { get; set; }
        public string NoteDisplayPicture { get; set; }
        public string MemberDisplayPicture { get; set; }
        public string FacebookLink { get; set; }
        public string TwitterLink { get; set; }
        public string LinkedlnLink { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
